### ISSUE TITLE
Uncaught Error: Glsl: You must use a 'vec2 resolution' in your shader.

### ISSUE THREAD

**Issue by ninjasort** [gre/timelapse#1]
Would love to check this out, but I keep getting this error in the console after the build. Any ideas?

`Uncaught Error: Glsl: You must use a 'vec2 resolution' in your shader.`

**Comment by gre** [comment]
which browser & OS ?
Does the version [submitted here](http://js13kgames.com/games/timelapse/index.html) works ?
